---
- name: Create/update resources in Kubernetes
  k8s:
    context: "{{ k8s_kube_context }}"
    kubeconfig: "{{ k8s_kube_config }}"
    definition: "{{ lookup('template', item['name']) }}"
    state: "{{ item['state'] }}"
    # Ensure we see any failures in CI
    wait: yes
    validate:
      fail_on_error: yes
      strict: yes
  with_items: "{{ k8s_templates }}"
